<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Article;
use App\Models\Category;
use App\User;
use Faker\Generator as Faker;

$factory->define(Article::class, function (Faker $faker) {
    $title = $faker->sentence; // random sentence generated by Laravel
    return [
        'title' => $title,
        'slug' => str_slug($title),
        'body' => $faker->text,
        'category_id' => function () {
            return Category::all()->random();
        },
        'tags' => '',
        'close_to_comment' => rand(0, 1),
        'is_live' => rand(0, 1),

        'user_id' => function () {
            return User::all()->random();
        }
    ];
});
